### ISSUE TITLE
Don't spam repositories automated

### ISSUE THREAD

**Issue by frenck** [joelparkerhenderson/gender-inclusive-language#1]
Please don't spam repositories automated.

I'm pretty sure it's violating the terms and services of GitHub as well.

Example:

https://github.com/home-assistant/core/pull/68968

Thanks 👍 

../Frenck

EDIT: I now realize this repository might only have been providing some definitions and not responsible for that bot. Anyways, if not affiliated, at least you know what it is currently used for :)

**Comment by frenck** [comment]
Holy moly

![image](https://user-images.githubusercontent.com/195327/161032251-09dea093-572e-4b87-871e-b5953ea279c7.png)

**Comment by RyanCavanaugh** [comment]
It looks like the bot is authored by @jamiepinheiro

**Comment by jamiepinheiro** [comment]
@RyanCavanaugh based on feedback, the bot has been disabled. Apologies for any noise, if you'd like to open an issue on the bot's logic, feel free to do so here - https://github.com/inclusive-coding-bot/bot.

**Comment by RyanCavanaugh** [comment]
@jamiepinheiro I've looked at many of the bots PRs (for laughs) and it's clear this is not a tenable approach. Changing "Letterman" to "Letterperson" when it's someone's last name, de-pronouning specific individuals (which is **extremely** unacceptable BTW), changing 'he' (Hebrew's ISO identifier) to 'they', etc..

I appreciate the aims of the project but this just isn't something you can automate without an extremely sophisticated linguistics model, which this is obviously not doing. You've created a ton of noise for OSS maintainer.

**Comment by frenck** [comment]
Alright closing it on this end, as its not an issue for this repository.

**Comment by jamiepinheiro** [comment]
@RyanCavanaugh agreed. It seems much much advanced NLP work is required for this sort of bot to work correctly. Any open PRs have been manually verified and adjusted, and again, apologies for the noise.

**Comment by joelparkerhenderson** [comment]
Thanks @frenck for bringing this to attention here and showing what's happening. Thanks @RyanCavanaugh for stepping up for this item so fast-- I appreciate your help.

I'm the author & maintainer of this repo. I'm not aware of that bot or anything like it. If you find out more, I would be happy to have a constructive conversation with any of the bot developers or anyone else involved, because gender inclusive language is important, and being a good open source collaborator is also important. Thanks all!
